apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectiontest-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connectiontest-app
  template:
    metadata:
      labels:
        app: connectiontest-app
    spec:
      containers:
      - name: connection-test
        image: <your-registry>/connection-test:0.02
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 10m
            memory: 100Mi
        env:
        - name: COUCHBASE_CONN_STR
          value: "yourValue"
        - name: COUCHBASE_BUCKET
          value: "yourValue"
        - name: COUCHBASE_USER
          value: "yourValue"
        - name: COUCHBASE_PASSWORD
          value: "yourValue"
        - name: CONFLUENT_CONN_STR
          value: "yourValue"
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
      restartPolicy: Never